name: 'Automatic LÖVE packaging'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: nhartland/love-build@v1-beta2
      with:
      app_name: 'BubbleBlast'
      love_version: '11.3'
    - uses: actions/upload-artifact@v1
      with:
        name: built-applications
        path: 'release'
